version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:12
    branches:
          only:
            - master
    steps:
      - run:
          name: Install LFTP
          command: |
            sudo apt-get update;
            sudo apt-get install lftp;
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm i;
      - run:
          name: Run tests
          command: |
            npm run test;
      - run:
          name: Build
          command: |
            npm run build;
      - run:
          name: Send Via SFTP
          command: | 
            lftp sftp://${USERNAME}:${PASSWORD}@${HOSTNAME} -e "set sftp:auto-confirm yes; mirror -v -R --exclude .git/ --exclude .circleci/ ./build ./zachzimm.com/zachzimm.com/website/beta/; quit";
