import React from 'react';
import ProjectHeader from './ProjectHeader';
import Row from 'react-bootstrap/Row'
import Card from 'react-bootstrap/Card'
import { ProjectProps } from './ProjectHeader';
import { ProjectDetailsProps } from './ProjectDetails';

const ambientTrustDetails: ProjectDetailsProps = {
    dates: "May 2008 - May 2010",
    technologies: ["JavaScript, C, C#, MySQL, Arduino"],
    projectSites: [
        {url: "https://ethos.soic.indiana.edu/projects/ambient-trust", label: "ETHOS - Ambient Trust"},
        {url: "http://www.ljean.com/NetTrust/", label: "Net Trust"},
    ],
    sourcecode: [
        {url: "https://code.google.com/p/ambienttrust/", label: "Google Code - Ambient Trust"},
        {url: "https://code.google.com/p/nettrust/source/browse/branches/AmbientTrust/", label: "Google Code - Net Trust (branch)"},
        
    ],
    license: "Apache 2.0",
}

const ambientTrust: ProjectProps = {
    projectName:  'Ambient Trust',
    projectDetails: ambientTrustDetails,
}

export default function AmbientTrustProject() {
  
    return (
        <Card>
            <ProjectHeader {...ambientTrust}></ProjectHeader>
            <Row>
                <Card>
                    <h2>Description</h2>
                    <p>During my undergraduate studies I was chosen by Professor L. Jean Camp, the director of the Security Informatics Program at Indiana University, to have the opportunity of contributing to an open source project called Net Trust as part of a funded research assistantship made possible by Google and the National Science Foundation. My main contribution to this project was the design, maintenance, and development of an alternative interface called Ambient Trust. The goal of this alternative display was to simplify the information conveyed by an anti-phishing browser toolbar to a format more easily perceved by older adults (65 years old and above).</p>


                    <h2>Design</h2>
                    <p>Ambient Trust itself is a set of LED lights enclosed in a frosted plastic cube, with two arrows on the side of the cube that are touch responsive. The LEDs and frosted plastic blended the colors of the red and green LEDs to produce different shades of red, yellow and green. The color displayed by the cube represented the average of the user's friends' ratings of the current website being browsed in Firefox. If average rating was negative, the cube would pulse with a red color, indicating danger. If the rating was neutral the cube would glow yellow, and if the rating was positive the cube would glow green. The cube would also pulse red if SiteAdvisor or another third party rating authority deems a website a danger.</p>

                    <p>To rate a website (generally negatively), instead of interacting with the browser toolbar the user could touch the touch-sensitive arrows on the sides of the cube. Positive ratings are automatically generated by Net Trust based on how many times the user and his or her friends visited the website.</p>


                    <h2>Development</h2>
                    <p>The implementation of this project consisted of:</p>

                    <ul>
                        <li>An Arduino Microcontroller with multiple red and green LEDs soldered onto a custom shield attached to the microcontroller's board, with a layer of wax paper to help diffuse and blend light from the LEDs</li>
                        <li>Two capacitive touch sensors connected with wires soldered to the custom shield attached to the microcontroller board</li>
                        <li>A custom-fabricated frosted plastic cube with two metal arrows fitted with the two capacitive touch sensors</li>
                        <li>A small Arduino "sketch" developed in C to communicate with the browser toolbar via a USB Serial interface, monitor the touch sensors, and control all LEDs</li>
                        <li>A branched copy of Net Trust with modifications added to support the hardware</li>
                        <li>A program running on the user's machine called "Serproxy"</li>
                    </ul>
                </Card>
            </Row>
        </Card>
    );
  }